# Generated by Django 3.2.8 on 2021-10-25 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coins.coin')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcoming_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
